/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/aluno`; params?: Router.UnknownInputParams; } | { pathname: `/coordenador/CreateMonitoria`; params?: Router.UnknownInputParams; } | { pathname: `/coordenador/CreateNucleus`; params?: Router.UnknownInputParams; } | { pathname: `/coordenador`; params?: Router.UnknownInputParams; } | { pathname: `/coordenador/ListMonitorsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/monitor/CreateMonitoria`; params?: Router.UnknownInputParams; } | { pathname: `/monitor`; params?: Router.UnknownInputParams; } | { pathname: `/professor/CreateMonitoria`; params?: Router.UnknownInputParams; } | { pathname: `/professor/CreateNucleus`; params?: Router.UnknownInputParams; } | { pathname: `/professor`; params?: Router.UnknownInputParams; } | { pathname: `/professor/ListMonitorsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/profiles/profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CreateNoticeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CreateNucleusScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/RegisterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/aluno`; params?: Router.UnknownOutputParams; } | { pathname: `/coordenador/CreateMonitoria`; params?: Router.UnknownOutputParams; } | { pathname: `/coordenador/CreateNucleus`; params?: Router.UnknownOutputParams; } | { pathname: `/coordenador`; params?: Router.UnknownOutputParams; } | { pathname: `/coordenador/ListMonitorsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/monitor/CreateMonitoria`; params?: Router.UnknownOutputParams; } | { pathname: `/monitor`; params?: Router.UnknownOutputParams; } | { pathname: `/professor/CreateMonitoria`; params?: Router.UnknownOutputParams; } | { pathname: `/professor/CreateNucleus`; params?: Router.UnknownOutputParams; } | { pathname: `/professor`; params?: Router.UnknownOutputParams; } | { pathname: `/professor/ListMonitorsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/profiles/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CreateNoticeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CreateNucleusScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/RegisterScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/aluno${`?${string}` | `#${string}` | ''}` | `/coordenador/CreateMonitoria${`?${string}` | `#${string}` | ''}` | `/coordenador/CreateNucleus${`?${string}` | `#${string}` | ''}` | `/coordenador${`?${string}` | `#${string}` | ''}` | `/coordenador/ListMonitorsScreen${`?${string}` | `#${string}` | ''}` | `/monitor/CreateMonitoria${`?${string}` | `#${string}` | ''}` | `/monitor${`?${string}` | `#${string}` | ''}` | `/professor/CreateMonitoria${`?${string}` | `#${string}` | ''}` | `/professor/CreateNucleus${`?${string}` | `#${string}` | ''}` | `/professor${`?${string}` | `#${string}` | ''}` | `/professor/ListMonitorsScreen${`?${string}` | `#${string}` | ''}` | `/profiles/profile${`?${string}` | `#${string}` | ''}` | `/screens/CreateNoticeScreen${`?${string}` | `#${string}` | ''}` | `/screens/CreateNucleusScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/aluno`; params?: Router.UnknownInputParams; } | { pathname: `/coordenador/CreateMonitoria`; params?: Router.UnknownInputParams; } | { pathname: `/coordenador/CreateNucleus`; params?: Router.UnknownInputParams; } | { pathname: `/coordenador`; params?: Router.UnknownInputParams; } | { pathname: `/coordenador/ListMonitorsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/monitor/CreateMonitoria`; params?: Router.UnknownInputParams; } | { pathname: `/monitor`; params?: Router.UnknownInputParams; } | { pathname: `/professor/CreateMonitoria`; params?: Router.UnknownInputParams; } | { pathname: `/professor/CreateNucleus`; params?: Router.UnknownInputParams; } | { pathname: `/professor`; params?: Router.UnknownInputParams; } | { pathname: `/professor/ListMonitorsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/profiles/profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CreateNoticeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CreateNucleusScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
