/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/createMonitors` | `/createMonitors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/createNotice` | `/createNotice`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/init` | `/init`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/listMonitorsScreen` | `/listMonitorsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/noticeListScreen` | `/noticeListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/createMonitors` | `/createMonitors`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/createNotice` | `/createNotice`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/init` | `/init`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/listMonitorsScreen` | `/listMonitorsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/noticeListScreen` | `/noticeListScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/createMonitors${`?${string}` | `#${string}` | ''}` | `/createMonitors${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/createNotice${`?${string}` | `#${string}` | ''}` | `/createNotice${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/init${`?${string}` | `#${string}` | ''}` | `/init${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/listMonitorsScreen${`?${string}` | `#${string}` | ''}` | `/listMonitorsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/noticeListScreen${`?${string}` | `#${string}` | ''}` | `/noticeListScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/createMonitors` | `/createMonitors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/createNotice` | `/createNotice`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/init` | `/init`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/listMonitorsScreen` | `/listMonitorsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/noticeListScreen` | `/noticeListScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
